### ISSUE TITLE
JVM_EXTRA_OPTS need to be set to start

### ISSUE THREAD

**Issue by ricos-web** [goofball222/unifi#10]
Hi,

I can't start the container.  JVM_EXTRA_OPTS and JVM_INIT_HEAP_SIZE can't be unset
If I remove the variable container also doesn't start.
I can set JVM_INIT_HEAP_SIZE to 512M but what can I set for this parameter to start the container?

OS/distribution version: Synology DSM 6.2
Docker version: 17.05.0-0344
Labels from docker inspect goofball222/unifi:sc

Thanks
Rico

**Comment by goofball222** [comment]
JVM_EXTRA_OPTS and JVM_INIT_HEAP_SIZE are there for tuning only if needed and are set to null/blank by default when the container builds from the Dockerfile. If you're providing those as --env/-e flags to the container at launch with no parameters that's may be why it's complaining. You should be able to launch the container without specifying them as environment flags and the defaults will take over.

Can you provide a sanitized/no private paths, etc. example of the ```docker run``` command or docker-compose.yml file you're using to launch and the Labels section of the ```docker inspect goofball222/unifi:XX``` command, where "XX" is the tag you're using IE: ```docker inspect goofball222/unifi:sc``` 

```
"Labels": {
                "org.label-schema.build-date": "2017-10-13T06:01:39Z",
                "org.label-schema.license": "Apache-2.0",
                "org.label-schema.name": "UniFi Controller",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://github.com/goofball222/unifi",
                "org.label-schema.vcs-ref": "c996121",
                "org.label-schema.vcs-url": "https://github.com/goofball222/unifi.git",
                "org.label-schema.vendor": "goofball222",
                "org.label-schema.version": "5.6.19-17e4cda571"
            }
```

If you haven't yet I'd also recommend re-pulling the latest version of the container build for the version you need to make sure you're up-to-date.

**Comment by ricos-web** [comment]
I tried it again and removed the variables from the environment settings. This time the container starts without problems. Strange, the laste time I did this, I got errors regarding the variable.

Thanks for your help and that great work!
