### ISSUE TITLE
Local ports conflicts with other ports used by other services

### ISSUE THREAD

**Issue by sampl3x** [goofball222/unifi#11]
Since the new version i can't start the Docker container anymore on my Synology and gives "Local ports port {unify port numbers} conflicts with other ports used by other services.
I dont use Automatic port mapping, but map 10001 to 10001, 3478 to 3478, etc but now this doesn't work anymore.

**Comment by goofball222** [comment]
That error messaging indicates that some other service or application on your Synology NAS is using one or more of the ports you're trying to map. Make sure that you've stopped and removed all old versions of the container before trying to start a new/updated instance. For further troubleshooting you'd have to look through the output of `netstat -anop` or similar from the command line to see what's conflicting.

**Comment by sampl3x** [comment]
@goofball222 already looked at my Synology wiht netstat if something is running on those ports but nothing.. Also port scanner dont give my open Synology ports

**Comment by sampl3x** [comment]
Fixed it by deleting the files in  /var/lib/docker/network/files

**Comment by sampl3x** [comment]
Trying to update 5.7.10 and again the same issue :(

There a no file in the above directory anymore

**Comment by goofball222** [comment]
This has to be something going on in the Synology implementation of Docker, I'm not seeing this on any of my Ubuntu or Debian based Docker hosts. As far as the container setup/Dockerfile is concerned I'm not declaring anything special or out of the ordinary for port mappings. Unfortunately I don't have any advice for you on how to fix this.
