### ISSUE TITLE
JVM_EXTRA_OPTS

### ISSUE THREAD

**Issue by sampl3x** [goofball222/unifi#12]
Created a new Unifi docker image on my Synology wont let me Save and Launch the Docker image because it keeps asking me to enter information for the Environment variables: JVM_EXTRA_OPTS and JVM_INIT_HEAP_SIZE

Leaving both variables values empty is not allowed. Removing them and start the docker image result in _Docker container: Unifi stopped unexpectedly._ error.

Filling JVM_INIT_HEAP_SIZE with 512M  also result in _Docker container: Unifi stopped unexpectedly._ error.

**Comment by sampl3x** [comment]
@goofball222 What must i fill in for JVM_EXTRA_OPTS? leaving it empty is excepted.

**Comment by lancer73** [comment]
@sampl3x are you running this container on a Synology NAS?

I got the same errors (plus that the local ports seem to be taken). I think this is an error introduced in the latest Synology update.

When I run the container from the command line on my NAS, like noted in the documentation for this container, I have no problems (“sudo su -“ first to become root).

**Comment by sampl3x** [comment]
@lancer73 You are correct. DSM was updates and the Docker package i can see. So it has to do with one of those updates.

Fixed it by deleting the files in the directory /var/lib/docker/network/files

**Comment by goofball222** [comment]
This is something specific to the way that Synology is handling Docker containers. I haven't been able to replicated this problem on a standard Linux host running the latest versions of Docker. I might be able to fix it on the container side by pulling those variables but I'd rather not impact functionality for others for an OS/device issue.

**Comment by top-cg** [comment]
Hi guys,
I fixed the problem on my DSM by doing that : 
JVM_EXTRA_OPTS = " " (1 space)
JVM_INIT_HEAP_SIZE = "512M"
Worked without any other problem ... but I sent a message to the Synology support team.

**Comment by goofball222** [comment]
Closing, not a container issue.

**Comment by top-cg** [comment]
For information, Synology replied me and they are saying : 

a) Empty values have been blocked by the dev team 
b) They can't provide any explanation regarding why they blocked them
c) If there is any security justification they will publish a press release
d) They can't confirm if they will allow empty values in the future, but the request has been submitted to the dev team.

May I ask you to check in your future containers that declaring an " " (space) value will work ? This will allow us to "fix" the problem whatever Synology is doing in the next update.

Thanks

**Comment by sampl3x** [comment]
When i'm adding a space the container starts also.
When i remove the JVM_EXTRA_OPTS then Docker on synology wont allow me tp run the  containter :(

When removing the option JVM_EXTRA_OPTS bij Goofball222 on his container would solve our problem.

**Comment by top-cg** [comment]
> When removing the option JVM_EXTRA_OPTS bij Goofball222 on his container would solve our problem.

He will not change his container for something 100% Synology related ... and this is normal. This is Synology which is not implementing Docker like is should ... not Goofball which is doing something wrong in his container ;)

**Comment by goofball222** [comment]
Setting JVM_EXTRA_OPTS to a space will work and shouldn't break anything. I'm extremely hesitant to remove that ENV variable as it is there to allow fine-tuning adjustments to the JVM process inside the container to suit individual deployment needs.

Since it sounds like it can't be blank in the Synology Docker implementation JVM_INIT_HEAP_SIZE can be set to a reasonable number like 128M, 256M, or 512M depending on resources available on the host system. This affects the minimum amount of memory that the Java process inside the container allocates so setting it too high may waste resources.

I'll keep the issues with Synology and blank variables in mind when approving/making changes in the future.

**Comment by top-cg** [comment]
Thanks ! Keep you inform if Synology is giving me any useful info ;)

**Comment by sampl3x** [comment]
Thank you Goofball222

**Comment by top-cg** [comment]
Synology updated the Docker package to accept "empty" values.
Version 17.05.0-0366
