### ISSUE TITLE
Create 5.8 stable candidate release path

### ISSUE THREAD

**Issue by chrismccracken** [goofball222/unifi#14]
Unifi 5.8 now has a stable candidate release 5.8.16 (https://community.ubnt.com/t5/UniFi-Wireless-Beta/UniFi-5-8-16-Stable-Candidate-has-been-released/m-p/2345115). However, there is still a 5.7 release path as well (5.7.26 as of a few days ago).

Is there a plan to create a 5.8 sc tag to pull from?

**Comment by goofball222** [comment]
Done. 5.7 sc moved to unifi57 branch, 5.8 sc added to master branch.
