### ISSUE TITLE
Update unstable to 5.9.12?

### ISSUE THREAD

**Issue by mikestecker** [goofball222/unifi#17]
Do you mind updating the `unstable` build to 5.9.12?

Release notes here: https://community.ubnt.com/t5/UniFi-Beta-Blog/UniFi-SDN-Controller-5-9-12-Testing-has-been-released/ba-p/2418005

**Comment by goofball222** [comment]
I'll take care of this update later this evening. Thank you for letting me know it was out, for some reason the UBNT update e-mail for the new post never showed up.

**Comment by goofball222** [comment]
Based on the UBNT post, 5.9.12 is actually a testing release. I updated the master:testing/VERSION file and the container :testing tag is rebuilding with that version on Docker cloud/hub now. This was done in commit https://github.com/goofball222/unifi/commit/3518f99c959b6f12b7365174a983867859491ca5.
