### ISSUE TITLE
Version 5.9.16 statistics in dashboard bugged. @works on a cloud key (confirmed)

### ISSUE THREAD

**Issue by skandshus** [goofball222/unifi#18]
## Reporting bugs/issues

* When reporting a bug/issue:
    * Ensure that you are using the latest release.
    * Revert any custom modifications or environment varibles to insure they're not the cause.

* Please provide the following information:
    * OS/distribution version (command for your OS may differ):
    IE:
    ```bash
    user@host:~$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 16.04.3 LTS
    Release:        16.04
    Codename:       xenial
    ```

    * Docker version:
    IE:
    ```bash
    user@host:~$ docker --version
    Docker version 17.05.0-ce, build 89658be
    ```

    * Labels from container:
    IE:
    ```bash
    user@host:~$ docker inspect goofball222/unifi:<tagname>
    ...
                "Labels": {
                    "org.label-schema.build-date": "2017-10-23T18:06:18Z",
                    "org.label-schema.license": "Apache-2.0",
                    "org.label-schema.name": "UniFi Controller",
                    "org.label-schema.schema-version": "1.0",
                    "org.label-schema.url": "https://github.com/goofball222/unifi",
                    "org.label-schema.vcs-ref": "dc9ca9c",
                    "org.label-schema.vcs-url": "https://github.com/goofball222/unifi.git",
                    "org.label-schema.vendor": "goofball222",
                    "org.label-schema.version": "5.6.19"
                }
    ...
    ```

    * Details on how to reproduce the trouble, if available:

I am running your image on Synology docker.
I am running the 5.9.16 version.

In the top left corner it shows "ISP LOAD" in the docker image it says unknown. And it does not populate with data 

i have attached photo's of the problem where its running on a Docker image. and when it runs on a Unifi Cloud key, with the same controller version 5.9.16.
![2 2](https://user-images.githubusercontent.com/34062583/43122841-aa7fe504-8f22-11e8-876e-98b9cb4ab7a4.jpg)
![1 1](https://user-images.githubusercontent.com/34062583/43122843-aa971954-8f22-11e8-8995-a04df4d51e59.jpg)
![2](https://user-images.githubusercontent.com/34062583/43122844-aaafc7e2-8f22-11e8-91c3-e6bb03ab99fe.jpg)
![1](https://user-images.githubusercontent.com/34062583/43122847-aae7dc22-8f22-11e8-8f50-eebdc45acb9f.jpg)

**Comment by goofball222** [comment]
Unfortunately I don't have a USG to test with, so I'm not able to confirm this issue directly. Is it present in the v5.8.X release tags (sc, latest) as well?

On the off chance its something with the new v5.9.X curl dependency I updated the testing Dockerfile to keep that installed post-build - 6e1dd3eaa85c00277b4d80662b5619119307a9ab. Once that completes building on Docker cloud (should be available ~1h after this is posted) can you re-download/update your copy of the "testing" tag container and see if that clears the issue?

If you could please also make sure you're mapping all of the necessary ports to the running container instance - minimum required are 3478/udp, 8080, 8443, 8880, and 8843

**Comment by goofball222** [comment]
@skandshus I'm going to assume that this was resolved either by config changes or updates in the versions released after this. If it's still ongoing let me know and I'll reopen the issue.
