### ISSUE TITLE
ARM Support?

### ISSUE THREAD

**Issue by jonwilliams84** [goofball222/unifi#20]
Trying to run this on a RPi 3 running Stretch gives: 

standard_init_linux.go:190: exec user process caused "exec format error"

Are there any plans to support armhf builds?

Thanks in advance

**Comment by goofball222** [comment]
I'll look into it. Unfortunately the Docker automated build environment is all x86_64 so it's not a simple add.

**Comment by fmdlc** [comment]
Can I build this for ARM? Using GitHub actions is possible to run.

**Comment by goofball222** [comment]
Handled via GitHub action builds.

Debian image: linux/amd64
Alpine image: linux/amd64, linux/arm64, linux/arm/v7
Ubuntu image: linux/amd64,linux/arm64

Limited by MongoDB packages on what architectures are available for Debian and Ubuntu.
