### ISSUE TITLE
STUN service only binds to IPv6 when IPv6 exists in container

### ISSUE THREAD

**Issue by chrismccracken** [goofball222/unifi#21]
OS/distribution version (command for your OS may differ):

`Synology NAS, Diskstation Manager OS (linux)`

Docker version:

 `Docker version 17.05.0-ce, build 9f07f0e-synology`

Labels from container:

    ```json
            "Labels": {
                "org.label-schema.build-date": "2018-07-24T17:49:13Z",
                "org.label-schema.license": "Apache-2.0",
                "org.label-schema.name": "UniFi Controller",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://github.com/goofball222/unifi",
                "org.label-schema.vcs-ref": "50081dd",
                "org.label-schema.vcs-url": "https://github.com/goofball222/unifi.git",
                "org.label-schema.vendor": "The Goofball - goofball222@gmail.com",
                "org.label-schema.version": "5.8.25-34502471b9"
            }
    ```

Details on how to reproduce the trouble, if available:

- Container is running in `host` networking mode, no NAT.
```
host# netstat -an |grep 3478
udp6       0      0 :::3478                 :::*
```

- The following workaround to disable IPv6 on the JVM resolves the issue, the STUN service properly binds to the IPv4 interface: `JVM_EXTRA_OPTS='-Djava.net.preferIPv4Stack=true'`
```
host# netstat -an |grep 3478
udp        0      0 0.0.0.0:3478            0.0.0.0:*
```

**Comment by goofball222** [comment]
It does appear only bound to IPv6 on a netstat on my checks as well in both mapping and host network modes, but based on testing against my hosts it does pass through IPv4 traffic. I can't speak to the specifics of the Synology Linux setup, it's possible that the automatic IPv6/IPv4 internal translation Linux does is disabled by default on it? In any case this doesn't appear to be a problem with the container itself that I'm able to find.

If you're having issues with devices suddenly showing STUN errors in the interface it may be a result of upgrading to firmware v3.9.44.9186 on devices. Based on posts on the UBNT UniFi beta forum there is a bug present in that version that broke the STUN server address config when using the "Override inform host with controller hostname/IP" setting, and possibly other scenarios. The v3.9.45.9203 firmware fixed this, but you will need to force re-provision the devices to fix the configuration problem after updating.
