### ISSUE TITLE
Add new Stable Candidate tag for 5.9

### ISSUE THREAD

**Issue by mikestecker** [goofball222/unifi#22]
Can you add a new `sc59` tag for the newest 5.9.20 stable candidate? I only suggested the tag `sc59` since I know there is also a stable candidate version currently sitting at 5.8.28, and I noticed you were tracking the 5.8.x builds with the `sc` tag.

Here's the release notes for 5.9.20: https://community.ubnt.com/t5/UniFi-Beta-Blog/UniFi-SDN-Controller-5-9-20-Stable-Candidate-has-been-released/ba-p/2443623

Release notes for 5.8.28: https://community.ubnt.com/t5/UniFi-Beta-Blog/UniFi-SDN-Controller-5-8-28-Stable-Candidate-has-been-released/ba-p/2443775

**Comment by goofball222** [comment]
I added a branch for 5.8 and moved that stable candidate there, that new automated tag/container build should be completed soon. The 5.9 stable candidate has been loaded into the master sc tag and should be completed building shortly on Docker cloud as well.
