### ISSUE TITLE
add tcpdump

### ISSUE THREAD

**Issue by evanrich** [goofball222/unifi#23]
you're image deleted all the apt/dpkg folders and files, making it impossible to install additional packages

```
root@unifi-controller-59985457c-zzjw6:/usr/lib/unifi# apt install tcpdump
Reading package lists... Error!
E: Could not open file /var/lib/dpkg/status - open (2: No such file or directory)
E: The package lists or status file could not be parsed or opened.
root@unifi-controller-59985457c-zzjw6:/usr/lib/unifi# apt update
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Get:2 http://ftp.debian.org jessie-backports InRelease [166 kB]
Ign http://repo.mongodb.org jessie/mongodb-org/3.4 InRelease
Get:3 http://security.debian.org jessie/updates/main amd64 Packages [641 kB]
Get:4 http://repo.mongodb.org jessie/mongodb-org/3.4 Release.gpg [801 B]
Get:5 http://repo.mongodb.org jessie/mongodb-org/3.4 Release [2393 B]
Ign http://deb.debian.org jessie InRelease
Get:6 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:7 http://repo.mongodb.org jessie/mongodb-org/3.4/main amd64 Packages [11.8 kB]
Get:8 http://ftp.debian.org jessie-backports/main amd64 Packages [1172 kB]
Get:9 http://deb.debian.org jessie Release.gpg [2420 B]
Get:10 http://deb.debian.org jessie Release [148 kB]
Get:11 http://deb.debian.org jessie-updates/main amd64 Packages [23.0 kB]
Get:12 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Fetched 11.5 MB in 7s (1577 kB/s)
Reading package lists... Error!
E: Could not open file /var/lib/dpkg/status - open (2: No such file or directory)
E: The package lists or status file could not be parsed or opened.
```

I'm having STUN errors and would like to debug inside the pod (running in kubernetes) but can't install tcpdump.   Can you either add tcpdump to the image, or not delete /var/lib/dpkg/*?

Thanks

**Comment by goofball222** [comment]
It ends up being a whopping ~5MB space savings to nuke the apt and dpkg DBs... I changed the Dockerfiles for all of the current builds to stop doing that - https://github.com/goofball222/unifi/commit/807d1ddb54ec613ac8fff0b718ed456644de2b7b. You should hopefully be able to add tcpdump after-the-fact now. To keep the overall image size down and for security I won't be adding it to the default build.

You might also want to double-check which firmware you're using on your devices. There were STUN URL problems with v3.9.44.9186 - https://community.ubnt.com/t5/UniFi-Wireless-Beta/FIRMWARE-3-9-44-9186-for-UAP-USW-has-been-released/m-p/2437185/highlight/true#M70402
