### ISSUE TITLE
Request for unstable tag

### ISSUE THREAD

**Issue by khandelwalpiyush** [goofball222/unifi#25]
To include releases like

https://community.ubnt.com/t5/UniFi-Beta-Blog/UniFi-5-9-4-Unstable-has-been-released/ba-p/2339206

**Comment by goofball222** [comment]
The "unstable" tag on GitHub and Docker Hub comes and goes as UBNT releases new software versions as this image follows their release formatting. Current latest release is v5.9.26 which is considered a stable candidate ("sc" tag) by UBNT.

I highly recommend signing up for UBNT beta access and following the UniFi blog posts if you're not already so you're aware of what's going on with their releases.

Some further references for you:
* https://community.ubnt.com/t5/UniFi-Beta-Blog/UniFi-SDN-Controller-5-9-26-Stable-Candidate-has-been-released/ba-p/2489657 
* https://community.ubnt.com/t5/UniFi-Wireless-Beta/UniFi-Controller-Releases-Updated-Jun-27th-2018/m-p/2352894
* https://community.ubnt.com/t5/UniFi-Wireless-Beta/Notes-on-UniFi-releases-Beta-Edition/m-p/2117198
