### ISSUE TITLE
recreating container (with sep mongo) resets unifi

### ISSUE THREAD

**Issue by imajes** [goofball222/unifi#29]
hello!

I've setup unifi + unfi-db containers via compose. If I want to upgrade the unifi container, I should be able to stop it and recreate it, by running something like the following: `docker stop unifi && docker-compose up -d`.

*Expected behavior*: new version pops up, I log into Unifi Controller again and all is good. 

*Actual behavior*: dropped into the setup wizard.

UniFi db is in it's own container, and that mongo doesn't restart...

I see no evidence that any of the unifi data on disk changes during the recreate.

docker-compose.yml: https://gist.github.com/imajes/625d1be7e07938a3756603179b7ec979

*requested info*:

```bash
       % lsb_release -a   
       No LSB modules are available.
       Distributor ID:	Ubuntu
       Description:	Ubuntu 18.04.1 LTS
       Release:	18.04
       Codename:	bionic
```

* Docker version:
```bash
       % docker --version
       Docker version 18.06.1-ce, build e68fc7a
       docker-compose version 1.20.1, build 5d8c71b
 ```

* Labels from container:
```bash
    user@host:~$ docker inspect goofball222/unifi:<tagname>
    ...
            "Labels": {
                "org.label-schema.build-date": "2019-01-30T01:31:36Z",
                "org.label-schema.license": "Apache-2.0",
                "org.label-schema.name": "UniFi Controller",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://github.com/goofball222/unifi",
                "org.label-schema.vcs-ref": "dc2932a",
                "org.label-schema.vcs-url": "https://github.com/goofball222/unifi.git",
                "org.label-schema.vendor": "The Goofball - goofball222@gmail.com",
                "org.label-schema.version": "5.9.29"
            }
    ...
```

I've run out of ideas for how to further debug this. Any tips welcome.

**Comment by goofball222** [comment]
Might be a problem with having the 'DEBUG=true' environment variable set, the UniFi software picks that up as well and it has caused me some oddities in the past, I normally don't run with that enabled outside of troubleshooting startup or script issues. Beyond that I'm at a loss on this one. I'm running a similar setup to yours without issue through container restarts and upgrades. I've also fired up multiple test instances, both internal and external DB and stepped through setup on them with no issue during or after restart or recreate.

Is there anything in the container run logs showing any kind of error (docker-compose logs unifi/unifidb) before the restart/re-up or after? Check in the mapped volume for the UniFi "logs/server.log" as well.

**Comment by goofball222** [comment]
Scratch that last comment, I see your problem now as I'm modifying your docker-compose.yml to test with. Your unifi service volume setup is incorrect:

    volumes:
      # - /var/apps/unifi:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/apps/unifi/cert:/var/apps/unifi/cert
      - /var/apps/unifi/data:/var/apps/unifi/data
      - /var/apps/unifi/logs:/var/apps/unifi/logs

The proper internal container path to each location is under /usr/lib/unifi/, externally it doesn't matter. Try this instead:

    volumes:
      # - /var/apps/unifi:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/apps/unifi/cert:**/usr/lib/unifi/cert**
      - /var/apps/unifi/data:**/usr/lib/unifi/data**
      - /var/apps/unifi/logs:**/usr/lib/unifi/logs**

**Comment by imajes** [comment]
@goofball222 good catch, and would totally explain it. will let you know how that works out.

**Comment by imajes** [comment]
... and a quick update: had to do some juggling to ensure both containers were happy talking to the same db volume, but once done it works just fine -- so i'm going to assume we're set and it should automagically update. thanks! :)
