### ISSUE TITLE
Docker missing unstable

### ISSUE THREAD

**Issue by simonnelli** [goofball222/unifi#32]
Docker is missing the unstable release. Maybe old unused tags could be cleaned up as well (show up when pulling images with a docker GUI like Synology)

**Comment by goofball222** [comment]
Old tags have been cleaned up. Docker Hub/Cloud unfortunately doesn't have any way to expire or automate that that I'm aware of so it's a manual process...

5.11.10 Unstable are building on Docker Hub/Cloud should be up shortly (~1h after this comment). There were a couple of problems with changes that have arisen with the base Debian and Alpine images that I had to trigger, and then work around.
