### ISSUE TITLE
WebSocket Connection error

### ISSUE THREAD

**Issue by zyxep** [goofball222/unifi#34]
Hi,

I know there use to be a bug with "websocket connection error", but as i could see on a changelog from Ubiquiti, they fixed it "long" ago.

I'm currently running `goofball222/unifi:latest` which is `5.10.21 (Build: atag_5.10.21_11661)`
I currently mount these ports to the container:
`0.0.0.0:6789->6789/tcp, 0.0.0.0:8443->8443/tcp, 0.0.0.0:8843->8843/tcp, 0.0.0.0:8880->8880/tcp, 0.0.0.0:3478->3478/udp, 0.0.0.0:8888->8888/tcp, 8080/tcp, 10001/udp`

And running Mongo in a separated container.

Any idea how to fix this?

**Comment by goofball222** [comment]
Are you accessing the controller via cloud access when you get the websocket error (https://unifi.ubnt.com)?

**Comment by zyxep** [comment]
> Are you accessing the controller via cloud access when you get the websocket error (https://unifi.ubnt.com)?

i'm accessing through my own url on the server.
an Nginx is in front proxy to 8443.
My user is connected to the cloud access.

**Comment by goofball222** [comment]
This is a fairly old issue, please try with a newer version of the Debian-based image and UniFi software and open a new issue if the problem persists.
