### ISSUE TITLE
5.10.25 is now Stable

### ISSUE THREAD

**Issue by jkgtw** [goofball222/unifi#37]
Hi

Cloud you update to 5.10.25 please
https://community.ui.com/releases/UniFi-Network-Controller-Stable-5-10-25/fc76945d-c918-4d8d-8cd1-094d05287f45

Thanks!

**Comment by goofball222** [comment]
Awesome, not only does the new "community" software totally suck for anything resembling usability, it nuked the blog posts and e-mail notifications I was using to monitor releases...

Updated image should be available ~1h after this post. Thanks for giving me a heads-up.
