### ISSUE TITLE
[Request] Provide SC also in testing 

### ISSUE THREAD

**Issue by vistalba** [goofball222/unifi#41]
Hi

UniFi Controller version 5.11.38 is a release candidate. 
From my point of view, it should also be avaiable as `testing` as long as there is no newer testing release. Otherwise people like me using this tag stuck on 5.11.36 because this was the last testing release. So I've always to switch between different tags to get the most recent version.

testing = most recent testing release or SC (release candidate) of the current testing cycle if there is no newer testing release
5.11-sc = all 5.11.x releases as release/stable candidate AND also public releases (if there is no more recent stable candidate) -> so it should also include the 5.11.x release at the end... otherwise people will stuck on 5.11.38 as release candidate also if there is 5.11.99 avaiable as a general release.

Is this possible?

**Comment by goofball222** [comment]
The releases/tags of this Docker container try to follow the tagging conventions of the UI developers as closely as possible. Unfortunately that means that as releases evolve through stages on the UI side that various tags for this container will need to be used, especially for beta/early access versions.

It's highly recommended that if you're using the beta/early access versions that you create a UI community account, sign up for beta access, and track the https://community.ui.com/releases/ page so you know when to check for and switch Docker tags. This also gives you the opportunity to provide feedback to the UI developers in the case you experience any issues or have any comments regarding the software as each version progresses.

**Comment by vistalba** [comment]
I know that and i‘m part of the beta community. 
It‘s annoying to switch this docker tags in kubernetes environment. 

For me, 5.11.38 ist testing and SC until a new testing build is released on the beta community.

**Comment by goofball222** [comment]
I agree with the annoyance. I switched tagging around with this latest commit, created a 5.11 and 5.11-alpine tag that will track new 5.11 releases until UI declares a stable point release, at which point it will switch to tracking the latest stable point release, with new sc, testing, etc. releases being their own individual tags.

I feel this accomplishes basically what you requested. Let me know if you have any comments or input.

**Comment by vistalba** [comment]
Okay.. this is a better solution. I've to change tags but at least if I stay on a tag for a while I will run a stable release in the end.
