### ISSUE TITLE
Unifi 5.11-sc always restarting on docker/raspberrpi 4

### ISSUE THREAD

**Issue by nicedevil007** [goofball222/unifi#43]
Hey goofball,

I'm running a fresh installed Hypriot OS on my raspberry with docker / portainer.
The realy first container I wanted to start with was/is your image for 5.11.39 :)

Maybe it is just not compatible with ARM7?

I get this error in the logfiles: 

`# docker logs --tail 50 --follow --timestamps unifi
2019-08-24T15:36:27.728186585Z standard_init_linux.go:211: exec user process caused "exec format error"
`

![grafik](https://user-images.githubusercontent.com/17103076/63639829-b5446d80-c698-11e9-82f2-6d3416bceea0.png)

![grafik](https://user-images.githubusercontent.com/17103076/63639831-ba092180-c698-11e9-9408-37a4d2b5910f.png)

![grafik](https://user-images.githubusercontent.com/17103076/63639834-c2f9f300-c698-11e9-9d49-9bfa9ae12855.png)

![grafik](https://user-images.githubusercontent.com/17103076/63639836-c7bea700-c698-11e9-93ce-61398b7b0919.png)

![grafik](https://user-images.githubusercontent.com/17103076/63639838-cf7e4b80-c698-11e9-8bd7-1e3c281562bc.png)

![grafik](https://user-images.githubusercontent.com/17103076/63639841-d7d68680-c698-11e9-9d48-9c9874dad235.png)

**Comment by goofball222** [comment]
Unfortunately the images as they exist today aren't compatible with ARMv7 CPUs. I had poked at setting up builds for non x86 CPUs in the past, however at the time it wasn't clear how to accomplish it using the Docker Hub/Cloud build infrastructure. I also don't have anything set up to personally test/debug them on.

I would be happy to revisit it if there is demand for them and people willing to test and provide feedback.
