### ISSUE TITLE
5.12 label not pushed to docker hub

### ISSUE THREAD

**Issue by imajes** [goofball222/unifi#47]
@goofball222 looks like the 5.12 release lable isn't avail on dockerhub. ( i know you just did it, but in case somehow it's not in the job queue, here's an issue for it ;))

also, are you in the unifi discord?

**Comment by goofball222** [comment]
5.12 release is building on the Docker cloud system now, should be there in ~1h.

No, I'm not on the UniFi Discord server. Happy to join if you want to share an invite link.

**Comment by imajes** [comment]
@goofball222: perfect, and here: https://discord.gg/EnE6W4 (feel free to ping me when you're on it)
