### ISSUE TITLE
5.11 stable release: 5.11.47

### ISSUE THREAD

**Issue by chicheng** [goofball222/unifi#53]
Seems [5.11.47 moved to stable channel 6 days ago](https://community.ui.com/releases/UniFi-Network-Controller-5-11-47/bc6b27a7-ada4-4cb5-a162-c659ed755a9f).

Thanks for the great work. 👍

**Comment by mbnn** [comment]
5.11.48 moved to stable now ;)

**Comment by goofball222** [comment]
New UI community "feature" strikes again... UBNT has been changing the existing sc/rc posts to stable when things are released. 5.11.47 went stable yesterday afternoon - https://community.ui.com/releases/UniFi-Network-Controller-5-11-47/bc6b27a7-ada4-4cb5-a162-c659ed755a9f#comment/66085c53-948b-43d0-8938-28a51d8ad86a

Unfortunately when they do this it doesn't trigger any release notifications, and also makes it confusing to determine when things were actually released.

Latest commit updates 5.11 / latest to v5.11.47. Builds should be complete on Docker Cloud in ~1h after this comment.
