### ISSUE TITLE
unfi:5.13 - WPA3 test release

### ISSUE THREAD

**Issue by adubravac** [goofball222/unifi#57]
Since this is a testing release and as I understood a copy of the 5.12 version, I'd be interested in if there is any plan on implementing the following source as a 5.13 release:

https://community.ui.com/questions/FEATURE-WPA3-for-UniFi-Gen1-2-and-3-APs/cbb7d35e-2644-40a3-a2b8-db8a9c07d063

https://dl.ubnt-ut.com/teunis/wpa3/5.13.9/unifi_5.13.9-13440~pr-3517-1_ubuntu_sysvinit_all.deb

Needs an unifi account to access. For testing purposes in the provided files WPA3 is enabled and I hope there are many more users who'd like to test this new feature within their docker container without having to install it directly to machine. 

Since you've released a 5.13 for testing, I'd reconsider if you want to keep the version number as provided.

Regards

**Comment by goofball222** [comment]
Since this is a one-off or feature beta release for testing WPA3 support changes and not directly in the standard public/beta unstable, testing, sc, release paths creating and maintaining an image for it doesn't fit the scope of this container.
