### ISSUE TITLE
Remote syslog Server -> Log to this controller

### ISSUE THREAD

**Issue by Alanin** [goofball222/unifi#58]
Hello,

i have an issue with my local unifi network and the support asked me to provide support logs. they guided my to activate the syslog stuff and also the option to log to this controller.

![image](https://user-images.githubusercontent.com/1335755/76421187-95aa3380-63a3-11ea-8cb9-a1e28b80508d.png)

when downloading the Supportfiles using the GUI no syslog events are in the log. also the directory where the syslog files should be logged is empty.

is there something to open (port) or configure (image/container) to make the syslog stuff working?

thank you alot

**Comment by goofball222** [comment]
Looking at this - yet another setting/feature that UBNT hasn't documented. Awesome.

Looks like if you open/forward UDP 5514 - run command flag: `-p 5514:5514/udp` - to the container direct syslog should start working for you.

**Comment by Alanin** [comment]
Hello,

Thank you for your answer. I have already tried that, but no logs are ending up in the local syslog. i was also able to Telnet to the port, seems to work.

Also I have tried to use a remote syslog server, this was working. Was wondering if there is something that has to be done in the container itself. 

If there is something I can do to help, gimme a sign.

**Comment by goofball222** [comment]
It's working as expected for me on my lab controller running the 5.13-alpine-testing tag pulled from Docker Hub. Based on my setup here, logs sent to the controller will end up the default log volume `- ./logs:/usr/lib/unifi/logs` in the sub-directory `remote` named with the IP and MAC of the AP sending them.

You will need to insure that log volume is mapped/persistent, has a `remote` sub-directory, and has the correct permissions/ownership for the UID/GID the docker container runs as  (default for both is 999).

You say you tested and successfully connected with telnet which uses TCP. Telnet wouldn't be able to connect to a UDP port like this syslog/netconsole service listens on. Double-check your port mapping setup for 5514 in your run command/launcher/docker-compose file. It's also possible there's a service on that Docker host already listening on that port blocking the mapping.

**Comment by Alanin** [comment]
Really strange. I have rechecked everything, restarted and recreated the image several times, now its logging to the log/remote directory...

So everything is working. Thank you alot for your assistance!
