### ISSUE TITLE
SSL config

### ISSUE THREAD

**Issue by jes1417** [goofball222/unifi#60]
## Reporting bugs/issues

* When reporting a bug/issue:
    * Ensure that you are using the latest release.
    * Revert any custom modifications or environment varibles to insure they're not the cause.

* Please provide the following information:
    * OS/distribution version (command for your OS may differ):
    IE:
    ```bash
    user@host:~$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Debian
    Description:     Debian GNU/Linux 10 (buster)
    Release:        10
    Codename:      Buster
    ```

    * Docker version:
    IE:
    ```bash
    user@host:~$ docker --version
    Docker version 19.03.8, build afacb8b7f0
    ```

    * Labels from container:
    IE:
    ```bash
    user@host:~$ docker inspect goofball222/unifi:<tagname>
    ...
         "Labels": {
                "org.label-schema.build-date": "2020-03-24T03:37:53Z",
                "org.label-schema.license": "Apache-2.0",
                "org.label-schema.name": "UniFi Controller",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://github.com/goofball222/unifi",
                "org.label-schema.vcs-ref": "c9d0384",
                "org.label-schema.vcs-url": "https://github.com/goofball222/unifi.git",
                "org.label-schema.vendor": "The Goofball - goofball222@gmail.com",
                "org.label-schema.version": "5.13.10-202b4c03d0"
                }
    ...
    ```

    * Details on how to reproduce the trouble, if available:
No issues with the container, thank you for your hard work!

I cannot for the life of me figure out what or how to get my rapidssl cert to take in the container. I have tried many different combos using openssl to get it working and I am stuck I was wondering if there was anymore info on what I need to do to get the privkey.pem generated and also the fullchain.pem

thanks again I didnt know where else to ask

**Comment by jes1417** [comment]
Does anyone have any pointers out links I could follow?

**Comment by jes1417** [comment]
Does anyone have any pointers out links I could follow?

**Comment by goofball222** [comment]
https://www.rapidsslonline.com/blog/how-to-create-a-pem-file-from-your-ssl-certificates/

The private key needed to create the privkey.pem file is something that is typically only on the host where you generated & completed the certificate signing request.
