### ISSUE TITLE
[Help] What options to limit resources and i/o?

### ISSUE THREAD

**Issue by zilexa** [goofball222/unifi#61]
Just wondering if you have any special recommendations to run on low end systems, to limit the read/write to SSD (logfiles?) to keep the (very old) SSD healthy. And RAM? I see the variable to limit RAM but wondering what an acceptable amount is?

**Comment by goofball222** [comment]
You can use Docker runtime options to limit CPU and RAM: https://docs.docker.com/config/containers/resource_constraints/

Beyond that I don't really have any specific recommendations, it's going to depend entirely on how complex your setup is. https://help.ui.com/hc/en-us/articles/115006614927-UniFi-Server-Hardware-Database-Management
