### ISSUE TITLE
5.12.72 moved to stable 

### ISSUE THREAD

**Issue by chicheng** [goofball222/unifi#63]
https://community.ui.com/releases/UniFi-Network-Controller-5-12-72/9ac72983-5130-4f58-b3ba-909f4d4bb5f9

Just 1 day after RC release.

**Comment by goofball222** [comment]
Appreciate the heads-up. The UI release system on their community forum is abysmal at providing any kind of warning on these changes.

I updated the 5.12 stable image to 5.12.72 and created a release. They're building on Docker hub now and should be available in an hour or so.
