### ISSUE TITLE
cannot adopt devices

### ISSUE THREAD

**Issue by kdr1978** [goofball222/unifi#65]
**lsb_release -a**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

Docker version 19.03.11, build 42e35e61f3

Problem since Upgrading to 5.13.29 (from 5.12.72)

I'm not able to adopt devices to the Controller since last Week (Status: Server Reject in ssh console) and i get the follow Error Massage in the LOG:

unifi    | [2020-06-22T16:59:41,455] XXX <inform-32> ERROR [InformServlet] - Servlet.service() for servlet [InformServlet] in context with path [] threw exception [Servlet execution threw an exception] with root cause
unifi    | java.lang.ClassNotFoundException: javax.activation.DataSource
unifi    | 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
unifi    | 	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
unifi    | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
unifi    | 	at com.ubnt.service.mail.C.o00000(Unknown Source) ~[ace.jar:?]
unifi    | 	at com.ubnt.service.mail.A.o00000(Unknown Source) ~[ace.jar:?]
unifi    | 	at com.ubnt.service.b.B.new(Unknown Source) ~[ace.jar:?]
unifi    | 	at com.ubnt.service.b.B.o00000(Unknown Source) ~[ace.jar:?]
unifi    | 	at com.ubnt.service.b.B.o00000(Unknown Source) ~[ace.jar:?]
unifi    | 	at com.ubnt.service.b.B.o00000(Unknown Source) ~[ace.jar:?]
unifi    | 	at com.ubnt.service.devmgr.oOOo.o00000(Unknown Source) ~[ace.jar:?]
unifi    | 	at com.ubnt.service.devmgr.oOOo.Ôo0000(Unknown Source) ~[ace.jar:?]
unifi    | 	at com.ubnt.service.devmgr.oOOo.øO0000(Unknown Source) ~[ace.jar:?]
unifi    | 	at com.ubnt.net.InformServlet.o00000(Unknown Source) ~[ace.jar:?]
unifi    | 	at com.ubnt.net.InformServlet.service(Unknown Source) ~[ace.jar:?]
unifi    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543) [tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609) [tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818) [tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623) [tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
unifi    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
unifi    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.51.jar:8.5.51]
unifi    | 	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by kdr1978** [comment]
temporarly solved the issue:
docker exec -it unifi bash
update-alternatives --config java

There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
* 2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Choose java-8

<exit>
Restart Container

**Comment by goofball222** [comment]
I changed the 5.13+ Debian-base Dockerfile so it stops pulling in OpenJDK-11 unintentionally. New builds should be up on Docker Hub in ~2h from now if you'd like to confirm that your issue is fixed.

**Comment by kdr1978** [comment]
Thank you for the quick response. I updated my version and everything is working fine again.
