### ISSUE TITLE
6.0.20 went stable

### ISSUE THREAD

**Issue by mbnn** [goofball222/unifi#70]
Hello,

6.0.20 went stable last weekend, will this be coming to the latest branch in time soon? 👍 
Thank you.

**Comment by goofball222** [comment]
6.0.20 was promoted to "stable" by Ubiquiti on Monday, 9/14. I'm heavily debating following their lead on this one, 6.0 changes structure and design in the controller drastically. There are also a bunch of reports on the UI community release post and elsewhere about it causing network loops and broadcast storms on existing setups. It also hides/removes things like long term statistics, and just generally appears to have major issues.

https://community.ui.com/questions/Broadcast-storm-after-Unifi-controller-upgrade-to-6-0-20/0b924047-0632-4304-bada-4158a0a5349e

On top of all of this they just posted a new 6.0.22 RC/SC today that purports to fix the VLAN/network loop problem in "most" cases:
https://community.ui.com/releases/UniFi-Network-Controller-6-0-22/910ceffc-f0e9-4518-86c1-df5eeee34695

**Comment by goofball222** [comment]
I went ahead and rebuilt everything to add 6.0.20 as the 6.0 "stable" release, and update the stable candidate to 6.0.22.

I won't be moving 6.0 to the Docker "latest" tag until it's actually stable/functional, so if you want to target 6.0 you'll need to use that specific tag.
