### ISSUE TITLE
GitHub Actions for auto update

### ISSUE THREAD

**Issue by superjeng1** [goofball222/unifi#75]
Hi, I think we should have a GitHub Action in this repository to automatically update the version when new versions is made available. I think this is possible and would save the author time updating the images manually. I could come up with a pr if you would like. And also, 6.0.37 is just out, 6.1.26 is out for about two days now.

**Comment by goofball222** [comment]
Added GitHub actions for building. May look to extend them for automated version updates in the future.

**Comment by superjeng1** [comment]
That's good to see, since in my experience, GitHub actions builds way faster than docker hub. More over, it's possible to trigger multiple actions at once so building multiple images at once is possible, making it even faster.
