### ISSUE TITLE
6.0.43 is stable

### ISSUE THREAD

**Issue by mbnn** [goofball222/unifi#76]
Hello,

I believe https://community.ui.com/releases/UniFi-Network-Controller-6-0-43/b28bb453-927a-4dd8-82f7-40af28505510
6.0.43 is official and stable, you still have .41 as stable for 6.0 😀 Thanks

**Comment by superjeng1** [comment]
I can indeed confirm 6.0.43 has became stable. It was indeed release candidate before, but became stable now. @goofball222 Can you help update it? Thanks a lot!

**Comment by goofball222** [comment]
Commit 0452084 updates 6.0/official to 6.0.43 and closes this issue.
