### ISSUE TITLE
6.1.54 Beta Released

### ISSUE THREAD

**Issue by pozgo** [goofball222/unifi#77]
[https://community.ui.com/releases/UniFi-Network-Controller-6-1-54/f44aa98c-6714-408b-8900-5f125272fd17](https://community.ui.com/releases/UniFi-Network-Controller-6-1-54/f44aa98c-6714-408b-8900-5f125272fd17)

Please update beta channel

**Comment by goofball222** [comment]
Commit 4384e85 updates 6.1/beta to 6.1.54 and closes this. Updated images should be available on Docker Hub ~1h after this comment.
