### ISSUE TITLE
Container exits because su-exec/gosu is missing

### ISSUE THREAD

**Issue by JaCoB1123** [goofball222/unifi#87]
I'm getting the following log output with the latest-alpine and 6.1-alpine image:
```
[2021-06-27 21:24:56,924] <docker-entrypoint> INFO - Running recursive 'chown' on Docker overlay2 storage is **really** slow. This may take a bit.
[2021-06-27 21:24:56,989] <docker-entrypoint> ERROR - su-exec/gosu NOT FOUND. Run state is invalid. Exiting.
```

The ubuntu images are working

OS/distribution version (command for your OS may differ):
   
```bash
Distributor ID: Ubuntu          
Description:    Ubuntu 19.10    
Release:        19.10           
Codename:       eoan            
```

Docker version:
```bash
Docker version 19.03.13, build cd8016b6bc
```

Labels from container:

com.docker.compose.config-hash | c2561f16611bec0ec28bce26feb14069b0036b17fb9d9e7d584356a053956cc9
-- | -- 
com.docker.compose.container-number | 1
com.docker.compose.oneoff | False
com.docker.compose.project | unifi2
com.docker.compose.project.config_files | docker-compose.yml
com.docker.compose.project.working_dir | /home/jacob/docker/unifi2
com.docker.compose.service | app
com.docker.compose.version | 1.25.5
org.opencontainers.image.created | 2021-06-17T22:04:42.589Z
org.opencontainers.image.description | UniFi Controller
org.opencontainers.image.licenses | Apache-2.0
org.opencontainers.image.revision | 0c477380b006eef531fb91f49aab06d6fe903cf0
org.opencontainers.image.source | https://github.com/goofball222/unifi
org.opencontainers.image.title | UniFi Controller
org.opencontainers.image.url | https://github.com/goofball222/unifi
org.opencontainers.image.vendor | The Goofball - goofball222@gmail.com
org.opencontainers.image.version | 6.1.71-Alpine

**Comment by goofball222** [comment]
I just tested on Ubuntu 20.04.2 with all current updates, running the latest Docker version 20.10.7, build f0df350, and I'm unable to reproduce this with the latest-alpine, 6.1-alpine, or 6.3-alpine-beta images.

I went ahead and re-ran the GH build actions for 5.14, 6.0, 6.1, and the 6.2 images just in case there was a something off with an Alpine package during the 2021-06-17 build that has been fixed. Please grab the latest build of the image and try again. Beyond that all I can recommend is updating your Docker host environment to the latest LTS/stable versions of Ubuntu and Docker.

**Comment by goofball222** [comment]
Closing, no response. Assume fixed/non-issue now.

**Comment by pozgo** [comment]
This is still an issue with 6.4-alpine

**Comment by JaCoB1123** [comment]
I was unable to reproduce it with 6.4-alpine, when I tried. I upgraded from Ubuntu 18.04 to 20.04 in the meantime though, so maybe that's the underlying cause here?
